package chart;

public class ChartPanel extends javax.swing.JPanel {
    float a,b,c;
    /** Creates new form PanelWykresu */
    public ChartPanel() {
        initComponents();
    }
    public ChartPanel(float a, float b, float c) {
        initComponents();
        this.a = a; this.b=b; this.c=c;
    }
    
    
    protected void paintComponent(java.awt.Graphics g){
        java.awt.Dimension d = this.getPreferredSize();
        float dx=2.0f,dy=2.0f;
        float minX=-2.0f, maxX=2.0f;
        float minY=-2.0f, maxY=2.0f;
        float Sx= (maxX-minX)/d.width;
        float Sy= (maxY-minY)/d.height;
    float yr,xr;
    int ye;
   

    for(int i=1; i<d.width; i++){
           xr =i*Sx-dx;
           yr =a*xr*xr+b*xr+c;
           ye = d.height-(int)((yr+dy)/Sy);
           g.drawLine(i, ye, i, ye);        
        }
        
    g.drawLine((int)((-2.0+dx)/Sx), d.height-(int)((0+dy)/Sy), 
    			(int)((2.0+dx)/Sx), d.height-(int)((0+dy)/Sy));    
    g.drawLine((int)((0+dx)/Sx), d.height-(int)((-2+dy)/Sy), 
    			(int)((0+dx)/Sx), d.height-(int)((2+dy)/Sy));    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
